# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: quantitative.py
import sqlite3
from openai import OpenAI
from dotenv import load_dotenv
import os
load_dotenv()

client = OpenAI(
    api_key=os.environ.get("GEMINI_API_KEY"),
    base_url="https://generativelanguage.googleapis.com/v1beta/openai/"
)

SCHEMA_CONTEXT = """
Available tables:
- sales(id, region, product, revenue, date, units_sold)
- customers(id, name, industry, churn_date, satisfaction_score)
- employees(id, department, satisfaction_score, tenure_years)
"""

def validate_sql(query: str) -> dict:
    # Block any destructive SQL keywords before execution
    blocked = ["DROP", "DELETE", "UPDATE", "INSERT", "ALTER", "TRUNCATE"]
    for word in blocked:
        if word in query.upper():
            return {"valid": False, "reason": f"Blocked keyword: {word}"}
    if not query.strip().upper().startswith("SELECT"):
        return {"valid": False, "reason": "Only SELECT queries are permitted"}
    return {"valid": True, "reason": "OK"}

def generate_sql(query: str) -> dict:
    response = client.chat.completions.create(
        model="gemini-3.5-flash-lite",
        max_tokens=256,
        messages=[{
            "role": "user",
            "content": f"{SCHEMA_CONTEXT}\n\nGenerate a SQLite-compatible SQL query for: {query}\n\nIMPORTANT: Use SQLite syntax only. Use strftime('%Y-%m', date) instead of DATE_TRUNC. Return ONLY the SQL query, nothing else."
        }]
    )
    raw = response.choices[0].message.content.strip()
    # Strip markdown code fences if Gemini wraps SQL in ```sql ... ```
    if raw.startswith("```"):
        raw = raw.split("```")[1]
        if raw.lower().startswith("sql"):
            raw = raw[3:]
    sql = raw.strip()
    return {
        "sql": sql,
        "input_tokens": response.usage.prompt_tokens,
        "output_tokens": response.usage.completion_tokens
    }

def run(query: str) -> dict:
    sql_result = generate_sql(query)
    sql = sql_result["sql"]
    validation = validate_sql(sql)

    if not validation["valid"]:
        return {
            "answer": f"Query blocked: {validation['reason']}",
            "sql": sql, "rows": [], "validation": "FAILED",
            "input_tokens": sql_result["input_tokens"],
            "output_tokens": sql_result["output_tokens"]
        }

    try:
        conn = sqlite3.connect("./data/database.sqlite")
        cursor = conn.cursor()
        cursor.execute(sql)
        rows = cursor.fetchall()
        cols = [d[0] for d in cursor.description]
        conn.close()

        interpretation = client.chat.completions.create(
            model="gemini-3.5-flash-lite",
            max_tokens=512,
            messages=[{
                "role": "user",
                "content": f"The user asked: {query}\n\nSQL used: {sql}\n\nResults:\nColumns: {cols}\nData: {rows[:20]}\n\nProvide a clear, concise interpretation."
            }]
        )
        return {
            "answer": interpretation.choices[0].message.content,
            "sql": sql, "columns": cols, "rows": rows, "validation": "PASSED",
            "input_tokens": sql_result["input_tokens"] + interpretation.usage.prompt_tokens,
            "output_tokens": sql_result["output_tokens"] + interpretation.usage.completion_tokens
        }

    except Exception as e:
        return {
            "answer": f"Query execution failed: {str(e)}",
            "sql": sql, "rows": [], "validation": "ERROR",
            "input_tokens": sql_result["input_tokens"],
            "output_tokens": sql_result["output_tokens"]
        }
